memcached: 
  image: memcached:latest 
  restart: always
  ports:
    - "11211:11211"

rabbitmq: 
  image: rabbitmq:latest
  restart: always
  ports:
    - "5672:5672"
    - "15672:15672"

mongo: 
  image: mongo:latest
  restart: always
  ports:
    - "27017:27017"

mysql: 
  build: mysql  
  ports: 
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password 
  restart: always

boostui: 
  build: additional-services/emulator-ui
  links: 
    - "mongo:mongo"  
  ports:
    - "8082:8082" 
  restart: always

boostsoapapi: 
  build: additional-services/emulator-soap-api
  links: 
    - "mongo:mongo"  
  ports:
    - "8081:8081" 
  restart: always
